export const templateOptions = [
  {
    id: "orbit",
    name: "Orbit — Engineering velocity",
    description: "Dark, neon lines with a fast engineering SaaS vibe.",
    url: "https://templates.webform.site/orbit",
    preview: "/templates/orbit.html",
    thumbnail: "/templates/orbit.png",
  },
  {
    id: "yuna",
    name: "YUNA — Proactive Intelligence Platform",
    description: "High-contrast predictive platform with orange and blue energy.",
    url: "https://templates.webform.site/yuna",
    preview: "/templates/yuna.html",
    thumbnail: "/templates/yuna.png",
  },
  {
    id: "aether",
    name: "AETHER — Advanced Skincare",
    description: "Luxury skincare hero with glassmorphism, scrolly storytelling, and editorial layout.",
    url: "https://templates.webform.site/aether",
    preview: "/templates/aether.html",
    thumbnail: "/templates/aether.png",
  },
  {
    id: "forward",
    name: "Forward — Next Gen Finance",
    description: "Futuristic finance OS with kinetic hero, glass nav, and developer-focused sections.",
    url: "https://templates.webform.site/forward",
    preview: "/templates/forward.html",
    thumbnail: "/templates/forward.png",
  },
  {
    id: "suki",
    name: "Sarah — Model Portfolio",
    description: "Cinematic portfolio with spotlight interactions, editorial hero, and project grid.",
    url: "https://templates.webform.site/suki",
    preview: "/templates/suki.html",
    thumbnail: "/templates/suki.png",
  },
  {
    id: "cognitive",
    name: "Cognitive Future AI",
    description: "Enterprise AI consulting with neural-themed hero, product stories, and rich visuals.",
    url: "https://templates.webform.site/cognitive",
    preview: "/templates/cognitive.html",
    thumbnail: "/templates/cognitive.png",
  },
  {
    id: "aura",
    name: "Aura",
    description: "Ethereal landing layout with layered gradients and crisp hero framing.",
    url: "https://templates.webform.site/aura",
    preview: "/templates/aura.html",
    thumbnail: "/templates/aura.png",
  },
  {
    id: "archito",
    name: "Archito",
    description: "Architectural portfolio aesthetic with structured grids and bold type.",
    url: "https://templates.webform.site/archito",
    preview: "/templates/archito.html",
    thumbnail: "/templates/archito.png",
  },
  {
    id: "roar",
    name: "Roar",
    description: "High-impact brand page with aggressive gradients and loud callouts.",
    url: "https://templates.webform.site/roar",
    preview: "/templates/roar.html",
    thumbnail: "/templates/roar.png",
  },
  {
    id: "engineer-portfolio",
    name: "Engineer Portfolio",
    description: "Personal engineering portfolio with clean sections and project highlights.",
    url: "https://templates.webform.site/engineer-portfolio",
    preview: "/templates/engineer-portfolio.html",
    thumbnail: "/templates/engineer-portfolio.png",
  },
  {
    id: "flux",
    name: "Flux",
    description: "High-energy SaaS landing with motion-forward hero and bold CTAs.",
    url: "https://templates.webform.site/flux",
    preview: "/templates/flux.html",
    thumbnail: "/templates/flux.png",
  },
  {
    id: "lexora",
    name: "Lexora",
    description: "Premium brand storytelling with editorial typography and luxe gradients.",
    url: "https://templates.webform.site/lexora",
    preview: "/templates/lexora.html",
    thumbnail: "/templates/lexora.png",
  },
  {
    id: "gemini-motion",
    name: "Gemini Motion",
    description: "Cinematic motion-inspired layout with layered panels and kinetic cards.",
    url: "https://templates.webform.site/gemini-motion",
    preview: "/templates/gemini-motion.html",
    thumbnail: "/templates/gemini-motion.png",
  },
  {
    id: "faster",
    name: "Faster",
    description: "Performance-focused product page with crisp metrics and speed visuals.",
    url: "https://templates.webform.site/faster",
    preview: "/templates/faster.html",
    thumbnail: "/templates/faster.png",
  },
  {
    id: "form-design",
    name: "Form Design",
    description: "Form-first experience showcasing UI patterns and clean inputs.",
    url: "https://templates.webform.site/form-design",
    preview: "/templates/form-design.html",
    thumbnail: "/templates/form-design.png",
  },
  {
    id: "genlabs",
    name: "GenLabs",
    description: "AI lab aesthetic with gradient lab panels and data-forward sections.",
    url: "https://templates.webform.site/genlabs",
    preview: "/templates/genlabs.html",
    thumbnail: "/templates/genlabs.png",
  },
  {
    id: "archdigest",
    name: "Archdigest",
    description: "Architectural digest vibe with large imagery and grid-based storytelling.",
    url: "https://templates.webform.site/archdigest",
    preview: "/templates/archdigest.html",
    thumbnail: "/templates/archdigest.png",
  },
  {
    id: "clarity-yield",
    name: "Clarity Yield",
    description: "Fintech yield dashboard look with clean cards and trust signals.",
    url: "https://templates.webform.site/clarity-yield",
    preview: "/templates/clarity-yield.html",
    thumbnail: "/templates/clarity-yield.png",
  },
  {
    id: "kreona",
    name: "Kreona",
    description: "Creative studio layout with playful color blocking and portfolio grid.",
    url: "https://templates.webform.site/kreona",
    preview: "/templates/kreona.html",
    thumbnail: "/templates/kreona.png",
  },
  {
    id: "devforge",
    name: "DevForge",
    description: "Developer tooling landing with dark code aesthetic and feature highlights.",
    url: "https://templates.webform.site/devforge",
    preview: "/templates/devforge.html",
    thumbnail: "/templates/devforge.png",
  },
] as const;
